### ISSUE TITLE
Refactor project so it can be easily included in another project as a unitypackage

### ISSUE THREAD

**Issue by flarb** [brnkhy/MapzenGo#12]
I think we should somehow move all of the assets to a subfolder, like Assets/MapzenGo so that you could export that folder as a unity package and import it into another project. As it stands now, the files are all scattered around the root assets folder which makes it hard to import into other projects and modify.

**Comment by brnkhy** [comment]
Yes, that's a great idea. I always look over these stuff, thank you man
