### ISSUE TITLE
Allow for custom materials on each layer

### ISSUE THREAD

**Issue by flarb** [brnkhy/MapzenGo#13]
I modified the Factory class to have a material member:

public Material objectMaterial;

And then in each Factory's subclass, I assign that material to the mesh after it's created. I can merge this change in, I suppose. But it's a simple fix to make. That way you can easily change the color of the buildings, water, etc. upon creation.

**Comment by brnkhy** [comment]
Yea that'll make it easier to use I guess. We also need layer ordering (layer thing is already in the dev branch and coming to master tonite/tomorrow) as well but guess I'll create another issue for that. Thanks man!

**Comment by brnkhy** [comment]
done in be37aa5b04893a40753ac80791afd950c45b4a04
