### ISSUE TITLE
Tiles don't line up exactly

### ISSUE THREAD

**Issue by flarb** [brnkhy/MapzenGo#16]
Perhaps it's because I'm not using LoadImage, but I've noticed that the tiles don't always line up against eachother--there's usually a gap in-between map tiles.
![seams](https://cloud.githubusercontent.com/assets/305261/17950364/a04f64a4-6a0f-11e6-9e56-35b295bee682.png)

**Comment by brnkhy** [comment]
I believe this is a duplicate of #9 
I mean precision fixes should correct that as well

**Comment by brnkhy** [comment]
this should be fixed with double precision commits
