### ISSUE TITLE
Just running the BasicLoader scene gets null reference exceptions

### ISSUE THREAD

**Issue by flarb** [brnkhy/MapzenGo#17]
I get a bunch of Null Reference Exceptions when I run the Basic Loader in the latest version:

NullReferenceException: Object reference not set to an instance of an object
Assets.Models.Factories.BuildingFactory+<Create>c__Iterator1.MoveNext () (at Assets/MapzenGo/Models/Factories/BuildingFactory.cs:31)
System.Linq.Enumerable+<CreateSelectManyIterator>c__Iterator12`2[JSONObject,UnityEngine.MonoBehaviour].MoveNext ()
Assets.Tile.RunFactories (.JSONObject mapData) (at Assets/MapzenGo/Models/Tile.cs:94)
Assets.Tile+<ConstructAsync>c__AnonStorey38.<>m__15 (.JSONObject mapData) (at Assets/MapzenGo/Models/Tile.cs:70)
UniRx.Observer+Subscribe`1[JSONObject].OnNext (.JSONObject value) (at Assets/MapzenGo/Plugins/UniRx/Scripts/Observer.cs:164)
UniRx.Operators.ObserveOnObservable`1+ObserveOn_[JSONObject].OnNext_ (.JSONObject value) (at Assets/MapzenGo/Plugins/UniRx/Scripts/Operators/ObserveOn.cs:159)
UniRx.Scheduler+MainThreadScheduler+QueuedAction`1[JSONObject].Invoke (System.Object state) (at Assets/MapzenGo/Plugins/UniRx/Scripts/UnityEngineBridge/MainThreadScheduler.cs:203)
UniRx.InternalUtil.ThreadSafeQueueWorker.ExecuteAll (System.Action`1 unhandledExceptionCallback) (at
![errors](https://cloud.githubusercontent.com/assets/305261/18020986/4046d78c-6b99-11e6-9984-4d920690141b.jpg)

**Comment by brnkhy** [comment]
I checked that and turns out it's just a simple type check issue. I'll keep trying different coordinates now but in case I cant find a sample (it doesnt crash in paris for me), can you post the coordinates?

**Comment by brnkhy** [comment]
dcf33a774568df13dbce2ad60bb38c15ffb40fdb should fix that, it's on dev branch at the moment but I'll soon push it on main as well
