### ISSUE TITLE
Share materials with ground object

### ISSUE THREAD

**Issue by flarb** [brnkhy/MapzenGo#18]
The ground material is always instanced on the map tiles. This prevents ground tiles from being batched. I'd make a material member in the World class that you can drag a material to (The default Ground material, perhaps) and then assign this material to the ground as tiles are built. That way you aren't creating a new material instance for each ground tile.

**Comment by brnkhy** [comment]
I'll most likely create a new factory for map tiles and handle image related stuff there as well. Then yea we can have a base material there, just like other factories.

**Comment by brnkhy** [comment]
nevermind that previous post, I did it as you suggest. no need to go for complex solution for the simplest thing I guess (wasting so many hours like that these days)
fixed in a2bf8bbd241b12afdb4cc361abae38fc77989ded

**Comment by brnkhy** [comment]
on the master branch now
