### ISSUE TITLE
Offline data possibillity?

### ISSUE THREAD

**Issue by brickhawkins** [brnkhy/MapzenGo#20]
Hi, Thank you for sharing this
great job sir

I'm wondering if you could add feature for offline data map and saving the map mesh on editor? Openstreetmap can export specific area, and we can convert it into geojson with geojson.io, or Mapzen provide an extracted data geojson files, but i couldn't understand how to convert it to your tilemap because I'm not understand enough about the long/lat conversion.

Thank you very much, I'm sorry for my poor English

**Comment by brnkhy** [comment]
I did offline thing in my previous test project by simply saving json files locally.  That worked beautifully and was quite simple but had issues with cleaning those files when necessary etc. Guess I'll try that at first, we can move to something more complex if necessary later on, thanks mate!
I'll also have to work on those conversion related stuff, everybody seems to get lost there :(

**Comment by brnkhy** [comment]
pushed this on dev branch, it works but just that. simplest possible implementation; 55fc95662b2b65d803cc5fed95a799d1d95f326b
needs threading and stuff bad. still I'll push it on main branch soon as well.

**Comment by brickhawkins** [comment]
Wow, thank you so much sir
I will try it very soon.
