### ISSUE TITLE
Merge objects based on their type (using layers)

### ISSUE THREAD

**Issue by brnkhy** [brnkhy/MapzenGo#27]
now we have one object for all buildings under a tile
if we change that to one obj for standard buildings, one for hospitals one for religious buildings etc, we'll be able to use type materials on those objects as well.
There'll be a small performance hit but probably wont even be noticable

**Comment by johnsnook** [comment]
this seems to be working well in dev branch

**Comment by brnkhy** [comment]
pushed on master branch as well
